services:
  - type: web
    name: presence-monitoring-app
    env: python
    rootDir: .
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: "python backend/server.py"
    envVars:
      PYTHON_VERSION: 3.10
