services:
  - type: web
    name: presence-monitoring-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT

staticSites:
  - name: presence-monitor-frontend
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: "."
